name: python-functional-programming
channels:
  - conda-forge
dependencies:
  - attrs=19.3.0
  - black=19.10
  - graphviz=2.40.1
  - multipledispatch=0.6.0
  - pip
  - pyrsistent=0.16.0
  - python=3.8
  - python-graphviz=0.14
  - toolz=0.10.0
